### ISSUE TITLE
ValueError: fname must be a string or file handle

### ISSUE THREAD

**Issue by rdrighetto** [scipion-em/scipion-em-imod#268]
Reporting the issue here because it's where I first found the error, but I believe it might be a more fundamental issue:

The function `self.getExtraOutFile()` called here is returning a tuple instead of a string:
https://github.com/scipion-em/scipion-em-imod/blob/62d6905c130119b60d74ed17c998431063ce9833/imod/protocols/protocol_doseFilter.py#L145

Which results in the following error:
```
Traceback (most recent call last):
  File "/scicore/projects/scicore-p-structsoft/ubuntu/software/Miniconda3/miniconda3_python3.12.1/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 203, in run
    self._run()
  File "/scicore/projects/scicore-p-structsoft/ubuntu/software/Miniconda3/miniconda3_python3.12.1/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 254, in _run
    resultFiles = self._runFunc()
  File "/scicore/projects/scicore-p-structsoft/ubuntu/software/Miniconda3/miniconda3_python3.12.1/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 250, in _runFunc
    return self._func(*self._args)
  File "/scicore/projects/scicore-p-structsoft/ubuntu/software/Scipion/plugins_nobackup/scipion-em-imod/imod/protocols/protocol_doseFilter.py", line 147, in doseFilterStep
    utils.generateDoseFileFromDoseTS(ts, outputDoseFilePath)
  File "/scicore/projects/scicore-p-structsoft/ubuntu/software/Scipion/plugins_nobackup/scipion-em-imod/imod/utils.py", line 1002, in generateDoseFileFromDoseTS
    np.savetxt(doseFileOutputPath, np.asarray(doseInfoList), fmt='%f', delimiter=" ")
  File "<__array_function__ internals>", line 200, in savetxt
  File "/scicore/projects/scicore-p-structsoft/ubuntu/software/Miniconda3/miniconda3_python3.12.1/envs/scipion3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1548, in savetxt
    raise ValueError('fname must be a string or file handle')
ValueError: fname must be a string or file handle
```

It's not the only occurrence but it's where it is first called in the dose filter protocol.

**Comment by rdrighetto** [comment]
Turns out the problem was a subtle comma at the end of this line that should not be there:
https://github.com/scipion-em/scipion-em-imod/blob/62d6905c130119b60d74ed17c998431063ce9833/imod/protocols/protocol_doseFilter.py#L145
After removing it everything works fine.
