### ISSUE TITLE
imod ctf correction fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-imod#309]
It seems that the acquisition order is only implemented for non-imod ctf series. I have a restacked input TS (some 40, some 41 tilts) and input imod ctf estimation with 41 tilts. I get an error indicating that tiltSeries size is not matching the ctfTomoSeries size.
```
00001:   Traceback (most recent call last):
00002:     File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 207, in run
00003:       self._run()
00004:     File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 257, in _run
00005:       resultFiles = self._runFunc()
00006:     File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 253, in _runFunc
00007:       return self._func(*self._args)
00008:     File "/home/gsharov/soft/scipion-em-plugins/scipion-em-imod/imod/protocols/protocol_ctfCorrection.py", line 206, in convertInputsStep
00009:       self.generateDefocusFile(tsId, presentAcqOrders=presentAcqOrders)
00010:     File "/home/gsharov/soft/scipion-em-plugins/scipion-em-imod/imod/protocols/protocol_ctfCorrection.py", line 326, in generateDefocusFile
00011:       utils.generateDefocusIMODFileFromObject(ctfTomoSeries, defocusFilePath,
00012:     File "/home/gsharov/soft/scipion-em-plugins/scipion-em-imod/imod/utils.py", line 698, in generateDefocusIMODFileFromObject
00013:       round(tiltSeries[index].getTiltAngle(), 2),
00014:   AttributeError: 'NoneType' object has no attribute 'getTiltAngle'
00015:   Protocol failed: 'NoneType' object has no attribute 'getTiltAngle'
```

**Comment by JorMaister** [comment]
Should work now
