### ISSUE TITLE
TestImodReconstructionWorkflow fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-imod#59]
```
azazello@debian:~/soft/scipion3/software/em$ scipion3 tests imod.tests.test_protocols_imod.TestImodReconstructionWorkflow
Scipion v3.0.7 - Eugenius
Running tests....
Creating project at:  /home/azazello/ScipionUserData/projects/TestImodReconstructionWorkflow/project.sqlite
>>>> python3 /home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_sync_data.py --download tomo-em 
Selected datasets: tomo-em
Local copy of dataset tomo-em detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
** Running command: 'python3 /home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py "/home/azazello/ScipionUserData/projects/TestImodReconstructionWorkflow" "Runs/000002_ProtImportTs/logs/run.db" 2'
** Running command: 'python3 /home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py "/home/azazello/ScipionUserData/projects/TestImodReconstructionWorkflow" "Runs/000064_ProtImodTSNormalization/logs/run.db" 64'

*************** LAST 50 LINES OF THE LOG *********************                                                                                                             

RUNNING PROTOCOL -----------------
Hostname: debian
PID: 26137
pyworkflow: 3.0.13
plugin: imod
plugin v: 3.0.5
currentDir: /home/azazello/ScipionUserData/projects/TestImodReconstructionWorkflow
workingDir: Runs/000064_ProtImodTSNormalization
runMode: Continue
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
STARTED: convertInputStep, step 1, time 2021-05-08 20:10:13.219259
Traceback (most recent call last):
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 197, in run
    self._run()
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 248, in _run
    resultFiles = self._runFunc()
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 244, in _runFunc
    return self._func(*self._args)
  File "/home/azazello/soft/scipion-em-plugins/scipion-em-imod/imod/protocols/protocol_tsNormalization.py", line 175, in convertInputStep
    outputTsFileName = os.path.join(tmpPrefix, ts.getFirstItem().parseFileName())
AttributeError: 'TiltImage' object has no attribute 'parseFileName'
Protocol failed: 'TiltImage' object has no attribute 'parseFileName'
FAILED: convertInputStep, step 1, time 2021-05-08 20:10:13.228206
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 1/5)
```

**Comment by fede-pe** [comment]
Thanks for the update. Could this error be due to the scipion-em-tomo package is not up to date in the devel branch? Also this past week we have introduced some modifications in the datasets and in this plugin, so I recommend updating both. If the error persists I will look at it in detail.

**Comment by azazellochg** [comment]
Thanks, @fede-pe . I kow got a different error:
```
Verifying MD5s...
overview_wbp.em differs. Downloading new version. Next time use -v for more details.
EMPIAR-10164/TS_01_040_60.0.mrc differs. Downloading new version. Next time use -v for more details.
...done. Updated files: 2
** Running command: 'python3 /home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py "/home/azazello/ScipionUserData/projects/TestImodReconstructionWorkflow" "Runs/000002_ProtImportTs/logs/run.db" 2'
** Running command: 'python3 /home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py "/home/azazello/ScipionUserData/projects/TestImodReconstructionWorkflow" "Runs/000065_ProtImodTSNormalization/logs/run.db" 65'

*************** LAST 50 LINES OF THE LOG *********************                                                                                                             

RUNNING PROTOCOL -----------------
Hostname: debian
PID: 24546
pyworkflow: 3.0.13
plugin: imod
plugin v: 3.0.5
currentDir: /home/azazello/ScipionUserData/projects/TestImodReconstructionWorkflow
workingDir: Runs/000065_ProtImodTSNormalization
runMode: Continue
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
STARTED: convertInputStep, step 1, time 2021-05-26 19:51:42.650431
FINISHED: convertInputStep, step 1, time 2021-05-26 19:51:42.660427
STARTED: generateOutputStackStep, step 2, time 2021-05-26 19:51:42.672871
 . /home/azazello/soft/scipion3/software/em/imod-4.10.42/IMOD-linux.sh && /home/azazello/soft/scipion3/software/em/imod-4.10.42/bin/newstack -input Runs/000065_ProtImodTSNormalization/tmp/a/BBa.st -output Runs/000065_ProtImodTSNormalization/extra/a/BBa.st -bin 2 -imagebinned 1.0                                                               
ERROR: iiOpen - Opening file Runs/000065_ProtImodTSNormalization/tmp/a/BBa.st

ERROR: iiuOpen - Could not open 'Runs/000065_ProtImodTSNormalization/tmp/a/BBa.st'
Traceback (most recent call last):
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 197, in run
    self._run()
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 248, in _run
    resultFiles = self._runFunc()
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 244, in _runFunc
    return self._func(*self._args)
  File "/home/azazello/soft/scipion-em-plugins/scipion-em-imod/imod/protocols/protocol_tsNormalization.py", line 218, in generateOutputStackStep
    Plugin.runImod(self, 'newstack', argsNewstack % paramsNewstack)
  File "/home/azazello/soft/scipion-em-plugins/scipion-em-imod/imod/__init__.py", line 144, in runImod
    protocol.runJob(cmd, args, env=cls.getEnviron(), cwd=cwd)
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1389, in runJob
    self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/executor.py", line 65, in runJob
    process.runJob(log, programName, params,
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/utils/process.py", line 52, in runJob
    return runCommand(command, env, cwd)
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/utils/process.py", line 67, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/home/azazello/soft/miniconda3/envs/.scipion3env/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' . /home/azazello/soft/scipion3/software/em/imod-4.10.42/IMOD-linux.sh && /home/azazello/soft/scipion3/software/em/imod-4.10.42/bin/newstack -input Runs/000065_ProtImodTSNormalization/tmp/a/BBa.st -output Runs/000065_ProtImodTSNormalization/extra/a/BBa.st -bin 2 -imagebinned 1.0 ' returned non-zero exit status 1.
Protocol failed: Command ' . /home/azazello/soft/scipion3/software/em/imod-4.10.42/IMOD-linux.sh && /home/azazello/soft/scipion3/software/em/imod-4.10.42/bin/newstack -input Runs/000065_ProtImodTSNormalization/tmp/a/BBa.st -output Runs/000065_ProtImodTSNormalization/extra/a/BBa.st -bin 2 -imagebinned 1.0 ' returned non-zero exit status 1.
FAILED: generateOutputStackStep, step 2, time 2021-05-26 19:51:42.796190
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 2/5)

```

**Comment by azazellochg** [comment]
test works now
