### ISSUE TITLE
etomo interactive fails at the end

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-imod#80]
```
00014:   STARTED: runEtomoStep, step 1, time 2021-06-27 16:45:14.888683
00015:    . /home/azazello/soft/scipion3/software/em/imod-4.10.42/IMOD-linux.sh && /home/azazello/soft/scipion3/software/em/imod-4.10.42/bin/copytomocoms -name TS_03 -gold 10.000 -pixel 0.135 -rotation 85.300 -userawtlt -NamingStyle 0 -StackExtension ""
00016:   All command files successfully created
00017:    . /home/azazello/soft/scipion3/software/em/imod-4.10.42/IMOD-linux.sh && /home/azazello/soft/scipion3/software/em/imod-4.10.42/bin/etomo --fg TS_03.edf
00018:   starting Etomo with log in /home/azazello/.etomologs/etomo_err_Jun-27-164524.log
00019:   Traceback (most recent call last):
00020:     File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 197, in run
00021:       self._run()
00022:     File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 248, in _run
00023:       resultFiles = self._runFunc()
00024:     File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 244, in _runFunc
00025:       return self._func(*self._args)
00026:     File "/home/azazello/soft/scipion-em-plugins/scipion-em-imod/imod/protocols/protocol_etomo.py", line 103, in runEtomoStep
00027:       self.createOutput()
00028:     File "/home/azazello/soft/scipion-em-plugins/scipion-em-imod/imod/protocols/protocol_etomo.py", line 314, in createOutput
00029:       outputSetOfCoordinates3D = self._createSetOfCoordinates3D(volSet=outputAliSetOfTiltSeries,
00030:     File "/home/azazello/soft/scipion-em-plugins/scipion-em-tomo/tomo/protocols/protocol_base.py", line 64, in _createSetOfCoordinates3D
00031:       coord3DSet.setPrecedents(volSet)
00032:     File "/home/azazello/soft/scipion-em-plugins/scipion-em-tomo/tomo/objects.py", line 1017, in setPrecedents
00033:       if precedents.isPointer():
00034:   AttributeError: 'NoneType' object has no attribute 'isPointer'
00035:   FAILED: runEtomoStep, step 1, time 2021-06-27 16:58:31.777279
```

**Comment by fede-pe** [comment]
Sorry, missed this one. Should be fixed now in devel branch. Thanks for reporting.
